# Generated by Django 4.2 on 2023-04-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_foodproduct_image_favorite_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foodproduct')),
                ('productIngredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='ingredients',
            field=models.ManyToManyField(through='main.ProductsIngredients', to='main.ingredients'),
        ),
    ]
