# Generated by Django 4.2 on 2023-04-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_foodproduct_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproduct',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ingredients'),
        ),
    ]
