# Generated by Django 4.2 on 2023-04-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_foodproduct_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproduct',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='main.ingredients'),
        ),
    ]
