# Generated by Django 4.2 on 2023-05-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_foodproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproduct',
            name='image',
        ),
    ]
