# Generated by Django 4.2 on 2023-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_foodproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='image',
            field=models.ImageField(default='static/food_products/default', upload_to='static/food_products/'),
        ),
    ]
