# Generated by Django 4.2 on 2023-05-15 12:04

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('card_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('expiry_date', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('cvv_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
            ],
        ),
    ]
