# Generated by Django 4.2 on 2023-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Credit Card')], max_length=20, null=True),
        ),
    ]
