# Generated by Django 4.2 on 2023-05-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_cart_text_box_obs_cartobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
