# Generated by Django 4.2 on 2023-06-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_order_product'),
        ('main', '0019_order_obs'),
    ]

    operations = [
    ]
