# Generated by Django 4.2 on 2023-06-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_0017_order_product_0019_order_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
