# Generated by Django 4.2 on 2023-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_categoria_foodproduct_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, default='active', max_length=20),
        ),
    ]
